name: ACwifidude-23.05-nss-qsdk11

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      
    - name: compile
      uses: thinkcyy/Action_OpenWrt_composite@compile
      with:           
           # RELEASE_PREFIX: "[Cron]"
           ROUTER_MODEL: EA8500
           COMPILE_CONFIG_BASE: ACwifidude-ipq806x
           COMPILE_CONFIG_DIFF: "common.cust.package.diff common.cust.package-1-OpenWrt_Component common.cust.package-2-luci_app common.cust.package-3-netfilter common.cust.package-4-nss"
           COMPILE_CONFIG: common.usb.diff
           # CONFIG_TO_ADD: "CONFIG_ALL_KMODS=y"
           CONFIG_TO_DEL: "CONFIG_PACKAGE_bc"
           REPLACE_IB: y
           IMAGEBUILDER: y
           REPO_TYPE: zhKong
           OP_REPO: ACwifidude/openwrt
           REPO_BRANCH: openwrt-23.05-nss-qsdk11
           CUSTOM_FEEDS_SH: custom_feeds-AgustinLorenzo
           # CONFIG_TO_DEL: "CONFIG_PACKAGE_kmod-nft-netdev CONFIG_PACKAGE_kmod-macvlan"
           token: ${{ secrets.GITHUB_TOKEN }} 
