name: ACwifidude-23.05-nss-qsdk11

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        
    - name: Initialization
      uses: thinkcyy/Action_Initialization@main               
                   
    - name: Prepare
      uses: thinkcyy/Action_OpenWrt_composite@prepare
      with:
           ROUTER_MODEL: EA8500
           COMPILE_CONFIG_BASE: common.cust.package.diff
           COMPILE_CONFIG_DIFF: "common.cust.package-1-OpenWrt_Component common.cust.package-2-luci_app common.cust.package-3-netfilter"
           #COMPILE_CONFIG_AUTOMERGE: common.cust.package
           COMPILE_CONFIG: common.cust.package-4-nss
           IMAGEBUILDER: y
           REPO_TYPE: zhKong
           OP_REPO: ACwifidude/openwrt
           #REPO_BRANCH: main_nss
           REPO_BRANCH: openwrt-23.05-nss-qsdk11
           #REPO_DATE: '2024-07-05T23:59:59+08:00'
           #REPO_DATE: 31e45f62cafbc9361c72d320241e589b31e2b5ed
           #DEFAULT_FEEDS: feeds.conf.default-20250225
           #EXTRA_FEEDS: add_feeds_cus_lean_luci
           CUSTOM_FEEDS_SH: custom_feeds-AgustinLorenzo
           #如果DEFAULT_FEEDS已自带HASH，MATCH_FEED_HASH要取消设定
           #MATCH_FEED_HASH: y
           #ACTION_DATE: fc19ca2
           #ACTION_DATE: '2024-07-03T23:59:59+08:00'
           #FEEDS_DATE:  '2024-10-23T23:59:59+08:00'
           
    - name: Replace IB
      working-directory: ${{ github.workspace }}/runner_root
      run: |
        cp -r imagebuilder ./openwrt/target/
           
    - name: Download package sources
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: make download V=s

    - name: Build tools
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make tools/install -j$(nproc) V=s || \
        make tools/install V=s
        
    - name: Build toolchain
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make toolchain/install -j$(nproc) V=s || \
        make toolchain/install V=s

    - name: Build target images
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      run: |
        make -j$(nproc) V=s || \
        make V=s

    - name: Upload
      uses: thinkcyy/Action_OpenWrt_composite@release
      
    - name: Create release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.TAG_NAME }}
        allowUpdates: true
        tag: ${{ env.TAG_NAME }}
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ./runner_root/artifact/*
